// <auto-generated />
using System;
using DraftSiteBE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DraftSiteBE.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260122190945_addingYarnEdits")]
    partial class addingYarnEdits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("DraftSiteBE.Models.LoomProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EndsInput")
                        .HasColumnType("INTEGER");

                    b.Property<double>("EndsPerCm")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("InputEndsInWarp")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .HasColumnType("TEXT");

                    b.Property<double>("PicksPerCm")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<double>("WarpLengthMeters")
                        .HasColumnType("REAL");

                    b.Property<decimal>("WeavingWidthCm")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WidthInput")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LoomProjects");
                });

            modelBuilder.Entity("DraftSiteBE.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastTagged")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("LoomProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("DraftSiteBE.Models.WarpChain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CrossCount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ends")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LoomProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<double>("WarpLength")
                        .HasColumnType("REAL");

                    b.Property<Guid>("YarnId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LoomProjectId");

                    b.HasIndex("YarnId");

                    b.ToTable("WarpChains");
                });

            modelBuilder.Entity("DraftSiteBE.Models.Yarn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("DyeLot")
                        .HasColumnType("TEXT");

                    b.Property<int>("FibreType")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LengthPerSkeinMeters")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("LoomProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NumberOfSkeins")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Ply")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("PricePerSkein")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ThicknessNM")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsageType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WeightPerSkeinGrams")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LoomProjectId");

                    b.ToTable("Yarns");
                });

            modelBuilder.Entity("DraftSiteBE.Models.YarnValidationSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlyMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlyMin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThicknessMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThicknessMin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("YarnValidationSettings");
                });

            modelBuilder.Entity("LoomProjectTag", b =>
                {
                    b.Property<Guid>("LoomProjectsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("TEXT");

                    b.HasKey("LoomProjectsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("LoomProjectTag");
                });

            modelBuilder.Entity("DraftSiteBE.Models.WarpChain", b =>
                {
                    b.HasOne("DraftSiteBE.Models.LoomProject", "LoomProject")
                        .WithMany("WarpChains")
                        .HasForeignKey("LoomProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DraftSiteBE.Models.Yarn", "Yarn")
                        .WithMany()
                        .HasForeignKey("YarnId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("LoomProject");

                    b.Navigation("Yarn");
                });

            modelBuilder.Entity("DraftSiteBE.Models.Yarn", b =>
                {
                    b.HasOne("DraftSiteBE.Models.LoomProject", "LoomProject")
                        .WithMany("Yarns")
                        .HasForeignKey("LoomProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("LoomProject");
                });

            modelBuilder.Entity("LoomProjectTag", b =>
                {
                    b.HasOne("DraftSiteBE.Models.LoomProject", null)
                        .WithMany()
                        .HasForeignKey("LoomProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DraftSiteBE.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DraftSiteBE.Models.LoomProject", b =>
                {
                    b.Navigation("WarpChains");

                    b.Navigation("Yarns");
                });
#pragma warning restore 612, 618
        }
    }
}
